# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\tmaru.auth\"=\n\x0f\x41llocRequestMsg\x12\x0c\n\x04size\x18\x01 \x01(\x04\x12\x0f\n\x07node_id\x18\x02 \x01(\r\x12\x0b\n\x03pid\x18\x03 \x01(\r\"\x85\x01\n\x10\x41llocResponseMsg\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tregion_id\x18\x02 \x01(\r\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x16\n\x0eserver_node_id\x18\x04 \x01(\r\x12\x12\n\nserver_pid\x18\x05 \x01(\r\x12\x12\n\nmount_path\x18\x06 \x01(\t\"C\n\x10\x41\x63\x63\x65ssRequestMsg\x12\x11\n\tregion_id\x18\x01 \x01(\r\x12\x0f\n\x07node_id\x18\x02 \x01(\r\x12\x0b\n\x03pid\x18\x03 \x01(\r\"J\n\x11\x41\x63\x63\x65ssResponseMsg\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rgranted_perms\x18\x02 \x01(\r\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\"\n\rGrantReadyMsg\x12\x11\n\tregion_id\x18\x01 \x01(\r\"7\n\x15GrantReadyResponseMsg\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xec\x01\n\x0b\x41uthService\x12G\n\x0c\x41llocRequest\x12\x1a.maru.auth.AllocRequestMsg\x1a\x1b.maru.auth.AllocResponseMsg\x12J\n\rAccessRequest\x12\x1b.maru.auth.AccessRequestMsg\x1a\x1c.maru.auth.AccessResponseMsg\x12H\n\nGrantReady\x12\x18.maru.auth.GrantReadyMsg\x1a .maru.auth.GrantReadyResponseMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLOCREQUESTMSG']._serialized_start=25
  _globals['_ALLOCREQUESTMSG']._serialized_end=86
  _globals['_ALLOCRESPONSEMSG']._serialized_start=89
  _globals['_ALLOCRESPONSEMSG']._serialized_end=222
  _globals['_ACCESSREQUESTMSG']._serialized_start=224
  _globals['_ACCESSREQUESTMSG']._serialized_end=291
  _globals['_ACCESSRESPONSEMSG']._serialized_start=293
  _globals['_ACCESSRESPONSEMSG']._serialized_end=367
  _globals['_GRANTREADYMSG']._serialized_start=369
  _globals['_GRANTREADYMSG']._serialized_end=403
  _globals['_GRANTREADYRESPONSEMSG']._serialized_start=405
  _globals['_GRANTREADYRESPONSEMSG']._serialized_end=460
  _globals['_AUTHSERVICE']._serialized_start=463
  _globals['_AUTHSERVICE']._serialized_end=699
# @@protoc_insertion_point(module_scope)
