# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from maru_common.proto import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Cold-path authentication service.
    Runs on a separate gRPC port with mTLS.
    Client identity is extracted from the mTLS peer cert SAN (SPIFFE ID),
    NOT from request fields — prevents role spoofing.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AllocRequest = channel.unary_unary(
                '/maru.auth.AuthService/AllocRequest',
                request_serializer=auth__pb2.AllocRequestMsg.SerializeToString,
                response_deserializer=auth__pb2.AllocResponseMsg.FromString,
                _registered_method=True)
        self.AccessRequest = channel.unary_unary(
                '/maru.auth.AuthService/AccessRequest',
                request_serializer=auth__pb2.AccessRequestMsg.SerializeToString,
                response_deserializer=auth__pb2.AccessResponseMsg.FromString,
                _registered_method=True)
        self.GrantReady = channel.unary_unary(
                '/maru.auth.AuthService/GrantReady',
                request_serializer=auth__pb2.GrantReadyMsg.SerializeToString,
                response_deserializer=auth__pb2.GrantReadyResponseMsg.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Cold-path authentication service.
    Runs on a separate gRPC port with mTLS.
    Client identity is extracted from the mTLS peer cert SAN (SPIFFE ID),
    NOT from request fields — prevents role spoofing.
    """

    def AllocRequest(self, request, context):
        """Owner requests region allocation.
        Server creates region, perm_set_default(0), perm_grant(ADMIN) to owner.
        Region enters CHOWN_PENDING state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccessRequest(self, request, context):
        """Reader requests access to an existing region.
        Server checks policy (role → perms), calls perm_grant.
        If region is CHOWN_PENDING, request is queued until GRANT_READY.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantReady(self, request, context):
        """Owner confirms CHOWN complete + GRANT re-granted to server.
        Region transitions CHOWN_PENDING → ACTIVE. Queued requests processed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AllocRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocRequest,
                    request_deserializer=auth__pb2.AllocRequestMsg.FromString,
                    response_serializer=auth__pb2.AllocResponseMsg.SerializeToString,
            ),
            'AccessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.AccessRequest,
                    request_deserializer=auth__pb2.AccessRequestMsg.FromString,
                    response_serializer=auth__pb2.AccessResponseMsg.SerializeToString,
            ),
            'GrantReady': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantReady,
                    request_deserializer=auth__pb2.GrantReadyMsg.FromString,
                    response_serializer=auth__pb2.GrantReadyResponseMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maru.auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('maru.auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Cold-path authentication service.
    Runs on a separate gRPC port with mTLS.
    Client identity is extracted from the mTLS peer cert SAN (SPIFFE ID),
    NOT from request fields — prevents role spoofing.
    """

    @staticmethod
    def AllocRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maru.auth.AuthService/AllocRequest',
            auth__pb2.AllocRequestMsg.SerializeToString,
            auth__pb2.AllocResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maru.auth.AuthService/AccessRequest',
            auth__pb2.AccessRequestMsg.SerializeToString,
            auth__pb2.AccessResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maru.auth.AuthService/GrantReady',
            auth__pb2.GrantReadyMsg.SerializeToString,
            auth__pb2.GrantReadyResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
