enable_pd: False
chunk_size: 256
local_cpu: False
save_unfull_chunk: True

# Maru backend
maru_path: "tcp://localhost:${MARU_SERVER_PORT}"
maru_pool_size: 4G

extra_config:
  lookup_backoff_time: 0.001
